# Change these first
owner: mattradford # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: ASN
    url: https://www.asn.org.uk
  - name: Mother
    url: $SECRET_SITE_1
    
assignees: # Users to assign downtime issues (optional)
  - mattradford

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a test status page for a couple of my websites. [**Get your own uptime monitor for free**](https://github.com/koj-co/upptime)
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
